openapi: 3.1.0
info:
  title: Gigs API
  version: 1.0.0
  description: API for managing gigs and users

paths:
  /gigs:
    post:
      summary: Create a new gig
      operationId: createGig
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                artist:
                  type: string
                spotifyArtistId:
                  type: string
                date:
                  type: date
                userId:
                  type: string
                venue:
                  type: string
              required:
                - artist
                - spotifyArtistId
                - date
                - userId
      responses:
        '201':
          description: Gig created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gig'
        '400':
          description: Invalid request

  /gigs/{id}:
    get:
      summary: Get a gig by ID
      operationId: getGigById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Gig found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gig'
        '404':
          description: Gig not found

  /users/{id}:
    get:
      summary: Get a user by ID
      operationId: getUserById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found

  /users/{id}/gigs:
    get:
      summary: Get gigs for a specific user
      operationId: getGigsForUser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of gigs for the user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Gig'
        '404':
          description: User or gigs not found

components:
  schemas:
    Gig:
      type: object
      properties:
        id:
          type: string
        artist:
          type: string
        venue:
          type: string
        userId:
          type: string
        spotifyArtistId:
          type: string
        date:
          type: date
    User:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
        upcomingPlaylistId:
          type: string
