name: deploy

on:
  [push, pull_request]
  # TODO: undo this after tested
  #push:
    #branches:
     # - master

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Cache Python dependencies
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Install UV
        run: |
          python -m pip install --upgrade pip
          pip install uv
      - name: Set up SAM CLI
        uses: aws-actions/setup-sam@v2
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Build
        run: |
          cd infra
          ./scripts/populate-sam-template.py -c ../functions/frontend_auth/app.js
          sam build --use-container -t template.inlined.yaml
      # Prevent prompts and failure when the stack is unchanged
      - name: Deploy to dev
        run: |
          cd infra
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --config-env dev
      - name: Integration test
        run: uv run pytest tests/integration