name: lint

on:
  [push, pull_request]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Set up SAM CLI
      uses: aws-actions/setup-sam@v2
    - name: Set up Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: "22.17"
    - name: Cache node modules
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Set up node modules
      run: |
        cd frontend
        npm ci
    - name: Install UV
      run: |
        python -m pip install --upgrade pip
        pip install uv
    - name: Lint Python files
      run: |
        uv run ruff check
    - name: Lint SAM templates
      run: |
        cd infra
        ./scripts/populate-sam-template.py -c ../functions/frontend_auth/app.js
        sam validate --lint -t template.inlined.yaml
        sam validate --lint -t shared/shared-infra.yaml
    - name: Lint Angular project
      run: |
        cd frontend
        npm run ng lint