name: lint

on:
  [push, pull_request]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Set up SAM CLI
      uses: aws-actions/setup-sam@v2
    - name: Set up Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: "22.17"
    - name: Set up Angular dependencies
      run:
        cd frontend
        npm ci
    - name: Install UV
      run: |
        python -m pip install --upgrade pip
        pip install uv
    - name: Lint Python files
      run: |
        uv run ruff check
    # TODO: run script insertion before linting
    - name: Lint SAM templates
      run: |
        sam validate --lint -t infra/template.yaml
        sam validate --lint -t infra/shared/shared-infra.yaml
    - name: Lint Angular project
      run:
        cd frontend
        ng lint