name: lint

on:
  [push, pull_request]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Set up SAM CLI
      uses: aws-actions/setup-sam@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
    - name: Lint with flake8
      run: |
        uv run ruff check
    - name: Lint SAM template
      run: |
        sam validate --lint -t infra/template.yaml
        sam validate --lint -t infra/shared/shared-infra.yaml